export const QUOTES: string[] = [
  "The secret of getting ahead is getting started.",
  "Don't watch the clock; do what it does. Keep going.",
  "It always seems impossible until it's done.",
  "Success is the sum of small efforts repeated day in and day out.",
  "Hard work beats talent when talent doesn't work hard.",
  "Believe you can and you're halfway there.",
  "You don't have to be great to start, but you have to start to be great.",
  "The future depends on what you do today.",
  "Push yourself, because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Success doesn't just find you. You have to go out and get it.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "Dream bigger. Do bigger.",
  "Don't stop when you're tired. Stop when you're done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do something today that your future self will thank you for.",
  "Little things make big days.",
  "It's going to be hard, but hard is not impossible.",
  "Don't wait for opportunity. Create it.",
  "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
  "The key to success is to focus on goals, not obstacles.",
  "Dream it. Believe it. Build it.",
  "Challenges are what make life interesting. Overcoming them is what makes life meaningful.",
  "If you want to achieve greatness stop asking for permission.",
  "Things work out best for those who make the best of how things work out.",
  "To live a creative life, we must lose our fear of being wrong.",
  "If you are not willing to risk the usual, you will have to settle for the ordinary.",
  "Trust because you are willing to accept the risk, not because it's safe or certain.",
  "Take up one idea. Make that one idea your life.",
  "Success is liking yourself, liking what you do, and liking how you do it.",
  "Act as if what you do makes a difference. It does.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Never bend your head. Hold it high. Look the world straight in the eye.",
  "What you get by achieving your goals is not as important as what you become.",
  "When you have a dream, you've got to grab it and never let go.",
  "I can't change the direction of the wind, but I can adjust my sails.",
  "It is in your moments of decision that your destiny is shaped.",
  "Too many of us are not living our dreams because we are living our fears.",
  "I didn't fail the test. I just found 100 ways to do it wrong.",
  "If you're going through hell, keep going.",
  "We generate fears while we sit. We overcome them by action.",
  "Whether you think you can or you think you can't, you're right.",
  "The man who has confidence in himself gains the confidence of others.",
  "The only way to do great work is to love what you do.",
  "Magic is believing in yourself. If you can make that happen, you can make anything happen.",
  "All our dreams can come true, if we have the courage to pursue them.",
  "The real test is not whether you avoid this failure, because you won't.",
  "I find that the harder I work, the more luck I seem to have.",
  "The starting point of all achievement is desire.",
  "Success is the child of audacity.",
  "The difference between a successful person and others is not a lack of strength.",
  "Your time is limited, so don't waste it living someone else's life.",
  "The two most important days in your life are the day you are born and the day you find out why.",
  "Definiteness of purpose is the starting point of all achievement.",
  "We must be willing to let go of the life we planned so as to have the life that is waiting for us.",
  "Manage your energy, not your time.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Creativity is intelligence having fun.",
  "What we achieve inwardly will change outer reality.",
  "It does not matter how slowly you go as long as you do not stop.",
  "When everything seems to be going against you, remember that the airplane takes off against the wind.",
  "I am not a product of my circumstances. I am a product of my decisions.",
  "You can get everything in life you want if you will just help enough other people get what they want.",
  "Inspiration does exist, but it must find you working.",
  "Don't settle for average. Bring your best to the moment.",
  "Everything you've ever wanted is on the other side of fear.",
  "We can easily forgive a child who is afraid of the dark; the real tragedy is men who are afraid of the light.",
  "Believe in yourself. You are braver than you think.",
  "When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left.",
  "I'd rather attempt to do something great and fail than attempt nothing and succeed.",
  "Life is not measured by the number of breaths we take, but by the moments that take our breath away.",
  "If you want to lift yourself up, lift up someone else.",
  "I have been impressed with the urgency of doing. Knowing is not enough; we must apply.",
  "Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless.",
  "In order to succeed, we must first believe that we can.",
  "Efforts and courage are not enough without purpose and direction.",
  "Certain things catch your eye, but pursue only those that capture the heart.",
  "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears.",
  "No matter what you're going through, there's a light at the end of the tunnel.",
  "We become what we think about most of the time, and that's the strangest secret.",
  "The more you seek security, the less of it you have.",
  "Every day brings new choices.",
  "A year from now you may wish you had started today.",
  "You are never too old to set another goal or to dream a new dream.",
  "To see what is right and not do it is a lack of courage.",
  "Reading is to the mind as exercise is to the body.",
  "The secret of joy in work is contained in one word: excellence.",
  "To know how much there is to know is the beginning of learning to live.",
  "Real difficulties can be overcome; it is only the imaginary ones that are unconquerable.",
  "The only person you are destined to become is the person you decide to be.",
  "Go confidently in the direction of your dreams. Live the life you have imagined.",
  "When one door of happiness closes, another opens.",
  "The most common way people give up their power is by thinking they don't have any.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "An unexamined life is not worth living.",
  "Everything has beauty, but not everyone can see.",
  "How wonderful it is that nobody need wait a single moment before starting to improve the world.",
  "The unexamined life is not worth living.",
  "When the going gets tough, the tough get going.",
  "It's never too late to be what you might have been.",
  "Life is what we make it, always has been, always will be.",
  "The question isn't who is going to let me; it's who is going to stop me.",
  "When I was 5 years old, my mother always told me that happiness was the key to life.",
  "Life is about making an impact, not making an income.",
  "Whatever the mind of man can conceive and believe, it can achieve.",
  "Strive not to be a success, but rather to be of value.",
  "Two roads diverged in a wood, and I took the one less traveled by.",
  "I attribute my success to this: I never gave or took any excuse.",
  "You miss 100% of the shots you don't take.",
  "I've missed more than 9000 shots in my career. That's why I succeed.",
  "The most difficult thing is the decision to act, the rest is merely tenacity.",
  "Every strike brings me closer to the next home run.",
  "Definiteness of purpose is the starting point of achievement.",
  "Life isn't about finding yourself. Life is about creating yourself.",
  "Nothing is impossible, the word itself says 'I'm possible'!",
  "The secret is to work less as individuals and more as a team.",
  "No masterpiece was ever created by a lazy artist.",
  "Talent wins games, but teamwork and intelligence wins championships.",
  "There are two types of people who will tell you that you cannot make a difference.",
  "You must expect great things of yourself before you can do them.",
  "Motivation will almost always beat mere talent.",
  "Learn from the mistakes of others. You can't live long enough to make them all yourself.",
  "You may only succeed if you desire succeeding; you may only fail if you do not mind failing.",
  "Courage is resistance to fear, mastery of fear, not absence of fear.",
  "Only put off until tomorrow what you are willing to die having left undone.",
  "You have brains in your head. You have feet in your shoes.",
  "If the wind will not serve, take to the oars.",
  "You can't fall if you don't climb. But there's no joy in living your whole life on the ground.",
  "We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained.",
  "Too many of us are not living our dreams because we are living our fears.",
  "Happiness is not something readymade. It comes from your own actions.",
  "If you're offered a seat on a rocket ship, don't ask what seat. Just get on.",
  "Build your own dreams, or someone else will hire you to build theirs.",
  "I would rather die of passion than of boredom.",
  "A truly rich man is one whose children run into his arms when his hands are empty.",
  "Success is not the key to happiness. Happiness is the key to success.",
  "People often say that motivation doesn't last. Well, neither does bathing.",
  "Life shrinks or expands in proportion to one's courage.",
  "If you can dream it, you can achieve it.",
  "The question is not who is going to let me, it's who is going to stop me.",
  "When it is obvious that the goals cannot be reached, don't adjust the goals, adjust the action steps.",
  "We become what we think about.",
  "Twenty years from now you will be more disappointed by the things you didn't do.",
  "The more that you read, the more things you will know.",
  "The most courageous act is still to think for yourself. Aloud.",
  "We must not allow the clock and the calendar to blind us.",
  "The truth is that our finest moments are most likely to occur when we are feeling deeply uncomfortable.",
  "Change your thoughts and you change your world.",
  "Either write something worth reading or do something worth writing.",
  "Nothing will work unless you do.",
  "I always did something I was a little not ready to do.",
  "Fake it until you make it.",
  "Experience is one thing you can't get for nothing.",
  "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.",
  "Ask and it will be given to you; search, and you will find.",
  "We can't help everyone, but everyone can help someone.",
  "The best revenge is massive success.",
  "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.",
  "No one can make you feel inferior without your consent.",
  "I will not allow my life's light to be determined by the darkness around me.",
  "Perfection is not attainable, but if we chase perfection we can catch excellence.",
  "Life is 10% what happens to me and 90% of how I react to it.",
  "Intelligence plus character – that is the goal of true education.",
  "The only way to achieve the impossible is to believe it is possible.",
  "You can never cross the ocean until you have the courage to lose sight of the shore.",
  "Either you run the day, or the day runs you.",
  "Whether you think you can or you think you can't, you're right.",
  "The man who moves a mountain begins by carrying away small stones.",
  "Once you choose hope, anything's possible.",
  "You are what you do, not what you say you'll do.",
  "I am not afraid of storms, for I am learning how to sail my ship.",
  "The only journey is the one within.",
  "Good things come to those who sweat.",
  "Never let the fear of striking out keep you from playing the game.",
  "Money and success don't change people; they merely amplify what is already there.",
  "Your life only gets better when you get better.",
  "Not how long, but how well you have lived is the main thing.",
  "You only live once, but if you do it right, once is enough.",
  "The most wasted of all days is one without laughter.",
  "Make each day your masterpiece.",
  "You've got to get up every morning with determination if you're going to go to bed with satisfaction.",
  "Be yourself; everyone else is already taken.",
  "If you do what you've always done, you'll get what you've always gotten.",
  "Happiness is not by chance, but by choice.",
  "It is not what we get. But who we become, what we contribute… that gives meaning to our lives.",
  "If you want to test your memory, try to recall what you were worrying about one year ago today.",
  "Our greatest fear should not be of failure, but of succeeding at things in life that don't really matter.",
  "Why do we close our eyes when we pray, cry, kiss, dream? Because the most beautiful things in life are not seen but felt only by heart.",
  "The truth is that our finest moments are most likely to occur when we are feeling deeply uncomfortable.",
  "One small positive thought in the morning can change your whole day.",
  "Opportunities don't happen. You create them.",
  "Love your family, work super hard, live your passion.",
  "It is never too late to be what you might have been.",
  "Believe that you will succeed, and you will.",
  "You become what you believe.",
  "When obstacles arise, you change your direction to reach your goal, you do not change your decision to get there.",
  "Stop doubting yourself, work hard and make it happen.",
  "I never dreamed about success. I worked for it.",
  "Your attitude, not your aptitude, will determine your altitude.",
  "Success seems to be connected with action. Successful people keep moving.",
  "Just when the caterpillar thought the world was ending, he turned into a butterfly.",
  "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
  "What comes easy won't last long, and what lasts long won't come easy.",
  "The most beautiful thing you can wear is confidence.",
  "Be so good they can't ignore you.",
  "The only time you fail is when you fall down and stay down.",
  "Don't count the days; make the days count.",
  "You never fail until you stop trying.",
  "If you look at what you have in life, you'll always have more.",
  "Life is short, and it is here to be lived.",
  "If you hire people just because they can do a job, they'll work for your money.",
  "To succeed in life, you need two things: ignorance and confidence.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "Light tomorrow with today.",
  "Well done is better than well said.",
  "You've got to follow your passion. You've got to figure out what it is you love.",
  "Keep your face always toward the sunshine, and shadows will fall behind you.",
  "What you do speaks so loudly that I cannot hear what you say.",
  "You have to learn the rules of the game. And then you have to play better than anyone else.",
  "In the middle of every difficulty lies opportunity.",
  "The only disability in life is a bad attitude.",
  "Arriving at one goal is the starting point to another.",
  "I was always looking outside myself for strength and confidence.",
  "The struggle you're in today is developing the strength you need for tomorrow.",
  "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.",
  "Character cannot be developed in ease and quiet.",
  "Problems are not stop signs, they are guidelines.",
  "Once you have commitment, you need the discipline and hard work to get you there.",
  "The way to get started is to quit talking and begin doing.",
  "The distance between your dreams and reality is called action.",
  "When you arise in the morning, think of what a precious privilege it is to be alive.",
  "You've got to get up every morning with determination if you're going to go to bed with satisfaction.",
  "Do what you can with all you have, wherever you are.",
  "One of the lessons that I grew up with was to always stay true to yourself.",
  "Now that I look back, I understand why my life turned out the way it did.",
  "It's hard to beat a person who never gives up.",
  "I wake up every morning and think to myself, 'how far can I push this company in the next 24 hours.'",
  "If people are doubting how far you can go, go so far that you can't hear them anymore.",
  "We need to accept that we won't always make the right decisions.",
  "Successful entrepreneurs are givers and not takers of positive energy.",
  "Whenever you see a successful person, you only see the public glories.",
  "Opportunities are usually disguised as hard work, so most people don't recognize them.",
  "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
  "I have not failed. I've just found 10,000 ways that won't work.",
  "If you're going through hell, keep going.",
  "Winning isn't everything, but wanting to win is.",
  "You may have to fight a battle more than once to win it.",
  "Creativity is knowing how to hide your sources.",
  "One of the great mistakes is to judge policies and programs by their intentions rather than their results.",
  "I don't want to get to the end of my life and find that I have just lived the length of it.",
  "Success is not in what you have, but who you are.",
  "The harder the conflict, the more glorious the triumph.",
  "Leadership is the capacity to translate vision into reality.",
  "We know what we are, but know not what we may be.",
  "Do one thing every day that scares you.",
  "Be the change that you wish to see in the world.",
  "Well-behaved women seldom make history.",
  "Logic will get you from A to Z; imagination will get you everywhere.",
  "A person who never made a mistake never tried anything new.",
  "You only live once, but if you do it right, once is enough.",
  "In three words I can sum up everything I've learned about life: it goes on.",
  "If you tell the truth, you don't have to remember anything.",
  "A friend is someone who knows all about you and still loves you.",
  "I've learned that people will forget what you said, people will forget what you did.",
  "Be yourself; everyone else is already taken.",
  "So many of our dreams at first seem impossible, then they seem improbable.",
  "Every child is an artist. The problem is how to remain an artist once he grows up.",
  "You can never cross the ocean until you have the courage to lose sight of the shore.",
  "I've learned that people will forget what you said, people will forget what you did.",
  "When one door of happiness closes, another opens.",
  "Do what you can, with what you have, where you are.",
  "If life were predictable it would cease to be life, and be without flavor.",
  "If you look at what you have in life, you'll always have more.",
  "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.",
  "Life is not measured by the number of breaths we take.",
  "If you want to live a happy life, tie it to a goal, not to people or things.",
  "Never let the fear of striking out keep you from playing the game.",
  "Money and success don't change people; they merely amplify what is already there.",
  "Your time is limited, so don't waste it living someone else's life.",
  "Not all those who wander are lost.",
  "The purpose of our lives is to be happy.",
  "Life is what happens when you're busy making other plans.",
  "You only live once, but if you do it right, once is enough.",
  "Many of life's failures are people who did not realize how close they were to success when they gave up.",
  "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.",
  "If life were predictable it would cease to be life, and be without flavor.",
  "If you want to live a happy life, tie it to a goal, not to people or things.",
  "Success is not the key to happiness. Happiness is the key to success.",
  "Work hard in silence, let your success be your noise.",
  "Turn your wounds into wisdom.",
  "If you can dream it, you can do it.",
  "The best way out is always through.",
  "Nothing is worth more than this day.",
  "In the middle of every difficulty lies opportunity.",
  "Courage is grace under pressure.",
  "There is no substitute for hard work.",
  "Do or do not. There is no try.",
  "Darkness cannot drive out darkness; only light can do that.",
  "Love the life you live. Live the life you love.",
  "Life is what we make it, always has been, always will be.",
  "The only way to do great work is to love what you do.",
  "You are never too old to set another goal or to dream a new dream.",
  "Anyone who has never made a mistake has never tried anything new.",
  "Strive not to be a success, but rather to be of value.",
  "Two roads diverged in a wood, and I took the one less traveled by.",
  "I attribute my success to this: I never gave or took any excuse.",
  "I've missed more than 9000 shots in my career. That's why I succeed.",
  "The most difficult thing is the decision to act, the rest is merely tenacity.",
  "Every strike brings me closer to the next home run.",
  "Life isn't about finding yourself. Life is about creating yourself.",
  "Nothing is impossible, the word itself says 'I'm possible'!",
  "The secret is to work less as individuals and more as a team.",
  "Talent wins games, but teamwork and intelligence wins championships.",
  "You must expect great things of yourself before you can do them.",
  "Motivation will almost always beat mere talent.",
  "Courage is resistance to fear, mastery of fear, not absence of fear.",
  "Only put off until tomorrow what you are willing to die having left undone.",
  "We must believe that we are gifted for something, and that this thing must be attained.",
  "Happiness is not something readymade. It comes from your own actions.",
  "If you're offered a seat on a rocket ship, don't ask what seat. Just get on.",
  "Build your own dreams, or someone else will hire you to build theirs.",
  "I would rather die of passion than of boredom.",
  "Success is not the key to happiness. Happiness is the key to success.",
  "People often say that motivation doesn't last. Well, neither does bathing.",
  "Life shrinks or expands in proportion to one's courage.",
  "The question is not who is going to let me, it's who is going to stop me.",
  "We become what we think about.",
  "The more that you read, the more things you will know.",
];

export function getDailyQuote(): string {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now.getTime() - start.getTime();
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24));
  return QUOTES[dayOfYear % QUOTES.length];
}
