/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BackgroundType = { 'color' : null } |
  { 'image' : null };
export interface Reminder {
  'id' : ReminderId,
  'title' : string,
  'isBirthday' : boolean,
  'isTriggered' : boolean,
  'dateTime' : Time,
}
export type ReminderId = bigint;
export interface ScheduleItem {
  'id' : bigint,
  'title' : string,
  'duration' : bigint,
}
export interface Target {
  'title' : string,
  'goalValue' : bigint,
  'currentValue' : bigint,
}
export type TaskId = bigint;
export type Time = bigint;
export interface UserProfile { 'username' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSettings {
  'backgroundType' : BackgroundType,
  'backgroundValue' : string,
}
export interface WeekTask {
  'id' : TaskId,
  'title' : string,
  'createdAt' : Time,
  'description' : string,
  'isComplete' : boolean,
}
export interface AssistantMessage {
  'id' : bigint,
  'role' : string,
  'text' : string,
  'createdAt' : Time,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addReminder' : ActorMethod<[string, Time, boolean], ReminderId>,
  'addScheduleItem' : ActorMethod<[string, bigint], bigint>,
  'addTask' : ActorMethod<[string, string], TaskId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteTask' : ActorMethod<[TaskId], undefined>,
  'exportUserData' : ActorMethod<
    [],
    {
      'tasks' : Array<WeekTask>,
      'scheduleTemplate' : Array<ScheduleItem>,
      'target' : [] | [Target],
      'settings' : [] | [UserSettings],
      'reminders' : Array<Reminder>,
    }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getReminders' : ActorMethod<[], Array<Reminder>>,
  'getScheduleTemplate' : ActorMethod<[], Array<ScheduleItem>>,
  'getTarget' : ActorMethod<[], [] | [Target]>,
  'getTasks' : ActorMethod<[], Array<WeekTask>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSettings' : ActorMethod<[], [] | [UserSettings]>,
  'getAssistantMessages' : ActorMethod<[], Array<AssistantMessage>>,
  'trackUserAction' : ActorMethod<[string, string], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setTarget' : ActorMethod<[string, bigint, bigint], undefined>,
  'setUserSettings' : ActorMethod<[BackgroundType, string], undefined>,
  'updateTask' : ActorMethod<[TaskId, string, string, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];