/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const ReminderId = IDL.Nat;
export const TaskId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const WeekTask = IDL.Record({
  'id' : TaskId,
  'title' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'isComplete' : IDL.Bool,
});
export const ScheduleItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
});
export const Target = IDL.Record({
  'title' : IDL.Text,
  'goalValue' : IDL.Nat,
  'currentValue' : IDL.Nat,
});
export const BackgroundType = IDL.Variant({
  'color' : IDL.Null,
  'image' : IDL.Null,
});
export const UserSettings = IDL.Record({
  'backgroundType' : BackgroundType,
  'backgroundValue' : IDL.Text,
});
export const Reminder = IDL.Record({
  'id' : ReminderId,
  'title' : IDL.Text,
  'isBirthday' : IDL.Bool,
  'isTriggered' : IDL.Bool,
  'dateTime' : Time,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addReminder' : IDL.Func([IDL.Text, Time, IDL.Bool], [ReminderId], []),
  'addScheduleItem' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
  'addTask' : IDL.Func([IDL.Text, IDL.Text], [TaskId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteTask' : IDL.Func([TaskId], [], []),
  'exportUserData' : IDL.Func(
      [],
      [
        IDL.Record({
          'tasks' : IDL.Vec(WeekTask),
          'scheduleTemplate' : IDL.Vec(ScheduleItem),
          'target' : IDL.Opt(Target),
          'settings' : IDL.Opt(UserSettings),
          'reminders' : IDL.Vec(Reminder),
        }),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
  'getScheduleTemplate' : IDL.Func([], [IDL.Vec(ScheduleItem)], ['query']),
  'getTarget' : IDL.Func([], [IDL.Opt(Target)], ['query']),
  'getTasks' : IDL.Func([], [IDL.Vec(WeekTask)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSettings' : IDL.Func([], [IDL.Opt(UserSettings)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setTarget' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'setUserSettings' : IDL.Func([BackgroundType, IDL.Text], [], []),
  'updateTask' : IDL.Func([TaskId, IDL.Text, IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const ReminderId = IDL.Nat;
  const TaskId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const WeekTask = IDL.Record({
    'id' : TaskId,
    'title' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'isComplete' : IDL.Bool,
  });
  const ScheduleItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
  });
  const Target = IDL.Record({
    'title' : IDL.Text,
    'goalValue' : IDL.Nat,
    'currentValue' : IDL.Nat,
  });
  const BackgroundType = IDL.Variant({
    'color' : IDL.Null,
    'image' : IDL.Null,
  });
  const UserSettings = IDL.Record({
    'backgroundType' : BackgroundType,
    'backgroundValue' : IDL.Text,
  });
  const Reminder = IDL.Record({
    'id' : ReminderId,
    'title' : IDL.Text,
    'isBirthday' : IDL.Bool,
    'isTriggered' : IDL.Bool,
    'dateTime' : Time,
  });
  const UserProfile = IDL.Record({ 'username' : IDL.Text, 'email' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addReminder' : IDL.Func([IDL.Text, Time, IDL.Bool], [ReminderId], []),
    'addScheduleItem' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
    'addTask' : IDL.Func([IDL.Text, IDL.Text], [TaskId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteTask' : IDL.Func([TaskId], [], []),
    'exportUserData' : IDL.Func(
        [],
        [
          IDL.Record({
            'tasks' : IDL.Vec(WeekTask),
            'scheduleTemplate' : IDL.Vec(ScheduleItem),
            'target' : IDL.Opt(Target),
            'settings' : IDL.Opt(UserSettings),
            'reminders' : IDL.Vec(Reminder),
          }),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
    'getScheduleTemplate' : IDL.Func([], [IDL.Vec(ScheduleItem)], ['query']),
    'getTarget' : IDL.Func([], [IDL.Opt(Target)], ['query']),
    'getTasks' : IDL.Func([], [IDL.Vec(WeekTask)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSettings' : IDL.Func([], [IDL.Opt(UserSettings)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setTarget' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'setUserSettings' : IDL.Func([BackgroundType, IDL.Text], [], []),
    'updateTask' : IDL.Func([TaskId, IDL.Text, IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };